### ISSUE TITLE
compatibility with scala.xml

### ISSUE THREAD

**Issue by fommil** [lihaoyi/scalatags#102]
there are many frameworks that only take the scala xml object types, it would be great if you could provide an implicit converter so that scalatags could be used as a drop-in replacement for literal XML.

**Comment by lihaoyi** [comment]
Sounds easy, just stringify it and parse it. Anyone want to volunteer an implementation =D

You can also go a more complex route by making your own Bundle that renders directly to `scala.xml.Elem` objects, instead of `scala.String`s or `html.Element`s that we have now. I wouldn't bother unless you found parsing was a bottleneck though

**Comment by lihaoyi** [comment]
Probably not going to happen as far as I can tell, given the lack of interest or activity. If you need it you can parse it for now

**Comment by bbarker** [comment]
Any suggestions for going in the other direction (Node or Elem -> Tag)?
