### ISSUE TITLE
Clarify rule of `bundle` package in docs.

### ISSUE THREAD

**Issue by metasim** [lihaoyi/scalatags#115]
The manual makes reference to the `bundle` package without explicitly defining what it is and where it comes from (at least as far as I could see).  I suggest adding something that indicates it is an object of type `scalatags.generic.Bundle`, and for the purposes of the examples can be defined with `import scalatags.{Text ⇒ bundle}` (for Scala JVM).

**Comment by stewSquared** [comment]
@metasim I don't think we should actually say `import scalatags.{Text ⇒ bundle}` in the docs, because that's not what's really happening. But I agree something more should be said. We could state the type of bundle earlier on (It's mentioned in the cross-backend section) and mention that `scalatags.Text` and `scalatags.JsDom` are interchangeable with it.
