### ISSUE TITLE
Support NodeSeq

### ISSUE THREAD

**Issue by alltonp** [lihaoyi/scalatags#66]
Hi,

Scalatags looks very interesting, I've been doing something similar but yours is much better!

I would like to use your DSL, for creating tags, but have it render to a NodeSeq. 

Is that possible right now? If not, would it be possible to support it?

Many thanks,

Paul

**Comment by marklister** [comment]
Scalatags supports outputing a tree of Dom elements:  https://github.com/lihaoyi/scalatags#dom-backend.  Would that be sufficient?

**Comment by lihaoyi** [comment]
I purposely got rid of the Scala-XML dependency. Can you just toString it and parse it? 

You could also subclass `Bundle` and add your own `Bundle[xml.Element, xml.Element]`. That's not hard, but it'd be more work than just stringifying and parsing the damn thing =P

**Comment by reid-spencer** [comment]
In my project, I validate the output scalatags with the [Nu Validator](https://github.com/validator/validator) which is necessary because HTML5 is NOT XML. Works For Me.

**Comment by lihaoyi** [comment]
Note that Scalatags outputs XTML and not HTML5. Not sure how materially different this will be for you, but that's the way it is

**Comment by alltonp** [comment]
I would really like to plug it in to my existing projects, which all use Liftweb with Scala-XML. I did think about toString and then parsing, but this feels a bit clunky and I imagine would be slow.

Subclassing Bundle sounds like the way to go, I'll look into that, do you have any examples?

**Comment by lihaoyi** [comment]
Don't imagine, go benchmark it! 

An example of a custom bundle is 
https://github.com/lihaoyi/scalatags/tree/master/js/src/main/scala/scalatags

Which instead of constructing `String`s, constructs `dom.Element`s You basically have to subclass `Bundle` and provide all the things it asks you to implement. Kind of boilerplatey, and maybe tricky getting the types to line up, but once the compiler is happy it should work
