### ISSUE TITLE
Possible to retain individual attributes

### ISSUE THREAD

**Issue by ramnivas** [lihaoyi/scalatags#68]
Is it possible to avoid fusing style-related attributes into one combined `style` attribute short of using `.attr` for each?

```scala
scala> import scalatags.Text.all._
import scalatags.Text.all._

scala> img(src := "foo", width := 10, height := 10)
res0: scalatags.Text.TypedTag[Nothing] = <img src="foo" style="width: 10;height: 10;" />

scala> img(src := "foo", "width".attr := 10, "height".attr := 10)
res1: scalatags.Text.TypedTag[Nothing] = <img src="foo" width="10" height="10" />
```

Is there a way to influence scalatags so that I can get `res1` with code like `img(src := "foo", width := 10, height := 10)`, perhaps by configuring the bundles?

**Comment by lihaoyi** [comment]
`width` and `height` are `Style` objects. You just need to define the `width` and `height` `Attr` objects (which is what you're doing above) and it will do what you want. Maybe put them in a custom bundle and use those instead of the styles from the `generic.Styles` traits. if you want all of them, you'll need to duplicate all the code we have in `generic.Styles`, annoying but straightforward.

Another alternative is to take 

https://github.com/lihaoyi/scalatags/blob/master/js/shared/main/scala/scalatags/Text.scala

And C&P it, overriding the `Builder` to use your own `Builder` which take `Style` objects and treats them the same as `Attrs`. This would be less lines of code but more complexity in those lines.

Are you really sure you know what you're doing though? Most styles make zero sense as attributes...

**Comment by ramnivas** [comment]
I will look into trying one of your suggestions.

As for why do I want to do this. I have been using Scalatags for a while (directly and also as a part of scalajs-react... in all cases it works really well. Thanks!). Recently, I switched a few [Scalate](https://github.com/scalate/scalate) templates to Scalatags. It too was a straightforward port, but I ran into an issue. I am serving my contents (an email notification in this case) through a layer of CDNs--first cloudflare and then Google's. Somewhere someone changed from `style="width: 1000;height: 1000;"` to `style="width: 1000;min-height: 1000;" and my images looked thin on small screens (smartphones). Since the working Scalate code had individual attribute and that looked fine on all devices, I did the same with Scalatags (added `".attr") and images looked fine again. There are still places where things don't look quite right and I suspect hitting the same kinds of issue. So I will have to do a whack-a-mole until I get it right. Thus wanted to know if there is any configuration option to do the same.

> Most styles make zero sense as attributes...

I am curious why you say that. Granted both approach should be equivalent, but defining them as attribute shouldn't be a problem either.

**Comment by lihaoyi** [comment]
> So I will have to do a whack-a-mole until I get it right. Thus wanted to know if there is any configuration option to do the same

Yeah the basic problem is that we have tried to squeeze three namespaces (Tags, Attributes, and Styles) into one (`import scalatags.Text.all._`). If you want to be *sure* you're doing things backwards-compatibly, you could try doing the manual-trascriptions of each thing to it's prefixed name: e.g. `attrs.width` when it's an attribute, `styles.width` when it's a style. Verbose but more certain especially when bulk-converting old code.

> I am curious why you say that. Granted both approach should be equivalent, but defining them as attribute shouldn't be a problem either.

They're equivalent for `width` and `height` (well not really, that's a lie, they're [pretty different](http://stackoverflow.com/questions/20742675/whats-the-difference-between-htmls-and-csss-width-attribute)), but I don't remember `backgroundColor` or `box-sizing` being valid attributes. Am I mistaken?

**Comment by ramnivas** [comment]
It really boils down to interpreting user intention. By `img(src := "foo", width := 10, height := 10)` does the user mean `<img src="foo" width="10" height="10" />` or `<img src="foo" style="width: 10;height: 10;" />`? Since most templating libraries do the former, that seems to be the default expectation for a user coming from one of those. Are those libraries doing it because they don't/can't reinterpret and process style-specific attributes in a special way or because they want to retain a direct translation? It is anyones guess.

Perhaps, there are two kinds of style attributes: ones that can be expressed as attributes and others that can't be (such as `backgroundColor` and `box-sizing`). Then the former could get a direct translation and others fused into a `style` attributes.

In any case, my use case is a narrow one for email notifications, since for everything else I pretty much rely on `className` along with CSS to get styling. Email messages, unfortunately, aren't conducive to using CSS stylesheets. Hence I ran into the issue. So you may close the issue unless there is something worth addressing in Scalatags based on this feedback.

**Comment by lihaoyi** [comment]
> It really boils down to interpreting user intention

It comes down to other templating libraries forcing you to put the styles under the style attributes manually `style="width: 10px; height: 10px"` (most of them) or `style: {width: 10, height: 10}` (React.js) and here me chucking it all together in one namespace, because there's *mostly* no overlap (width, height, title, etc. are exceptions)

How would you know if an attribute is fusible though? In a canvas or image `width` and `height` are standalone, everywhere else they're not. 

We probably just use our CSS differently. I for example have almost all my CSS widths and heights in-line, so it makes sense to have them conveniently available.

I think the way forward here is to use `styles.*` and `attrs.*` or define your own bundle without the bits you don't like ^_^

**Comment by lihaoyi** [comment]
In general this is the price we pay for the chuck-everything-in-one-namespace default

**Comment by ramnivas** [comment]
> How would you know if an attribute is fusible though? In a canvas or image width and height are standalone, everywhere else they're not.

That will require attributes to be context sensitive--which tags have which valid attributes and as what (a direct attribute or a style attribute). For example, currently, `tr(height := "10px")` is acceptable by Scalatags, but since `tr` doesn't support the `height` attribute, as a standalone attribute it is invalid and as a part of the `style` attribute or CSS it is ineffective. If attributes can be context-sensitive, in your canvas/image example, `width` and `height` could be mapped to direct attributes, but as `style` for other tags that could support it as a valid style attribute.

I don't know if this is possible with Scalatags or out of scope for a future version of Scalatags. But it will be wonderful if can be done. This will make Scalatags even more statically checked.

**Comment by lihaoyi** [comment]
> as a part of the style attribute or CSS it is ineffective

Wait why? CSS heights apply to tables too, don't they? Or am I mistaken?

It seems very hard to encode all the CSS precedence and acceptability rules into the Scala type system =P I know @propensive has done some work on it but for now Scalatags is a pretty thin syntactic layer

**Comment by ramnivas** [comment]
> CSS heights apply to tables too, don't they? Or am I mistaken?

Tables, perhaps `height` applies. For `tr` (the example tag I mentioned), `height` doesn't apply AFAIK (instead, you apply `height` to `td`s and I think `line-height` applies to `tr`). Messy! :-)

**Comment by propensive** [comment]
My experimental CSS work (maybe I'll finish it one day) wasn't doing anything especially clever with the type system - it was just a neat DSL to prevent spelling mistakes... I'd be intrigued to see if anyone managed to put something together that offered better type safety...

(Alongside this CSS work, I did implement a DSL which reasonably concisely represented HTML5 tags as function applications, and which correctly enforced basic nesting rules using the type system. So that could potentially form a basis for constraining CSS further, but I don't really hold out much hope of it coming to anything...)

**Comment by lihaoyi** [comment]
Ah, so it was HTML constraints that you had done, not CSS. I was mistaken.

**Comment by propensive** [comment]
I implemented a DSL for CSS too - which I think I showed you because it made some humorous use of overloading - though there was just nothing particularly clever about it! ;)
